"""
Storage interface protocols.

Both LocalRepository (SQLAlchemy) and a future RemoteRepository (HTTP client)
satisfy these interfaces via structural subtyping — no inheritance required.
Services only import from here, never from civex.db.
"""

from __future__ import annotations

from contextlib import AbstractContextManager

import uuid
from datetime import date, datetime
from pathlib import Path
from typing import (
    Any,
    AsyncIterable,
    Callable,
    ContextManager,
    Iterable,
    Iterator,
    Protocol,
    runtime_checkable,
)

from civex.domain.audit_filter import AuditFilter
from civex.domain.sync import (
    OpResult,
    SyncConflictDTO,
    SyncDeviceDTO,
    SyncInviteDTO,
    SyncEntry,
    SyncMetaDTO,
)
from civex.domain.dtos import (
    AiUsageEventDTO,
    AuditBatchDTO,
    AuditEventDTO,
    AuditLogDTO,
    DatasetDTO,
    FieldDTO,
    FileCopy,
    FileRef,
    RecordDTO,
    SchemaDTO,
    StoredObjectInfo,
    ViewDTO,
    ExportDefinitionDTO,
    VolumeStatus,
    WorkflowJobDTO,
)
from civex.domain.filters import FilterNode
from civex.domain.library import LibraryItemDTO
from civex.domain.query import ResolvedQuery
from civex.domain.transfers import CopyResult, TransferRecord

# (day, dataset_name, schema_name, count) -- see LocalRecordRepository.growth_by_period
RecordGrowthRow = tuple[date, str, str, int]
# (day, status, count) -- see LocalWorkflowJobRepository.status_counts_by_period
JobStatusRow = tuple[date, str, int]
# (bucket_start, plugin, count) -- already bucketed, see
# LocalWorkflowJobRepository.failure_counts_by_plugin
PluginFailureRow = tuple[str, str, int]
# (day, action, entity_type, count) -- see LocalAuditRepository.event_counts_by_period
AuditEventRow = tuple[date, str, str, int]
# (trigger, count) -- see LocalWorkflowJobRepository.trigger_counts
TriggerCountRow = tuple[str, int]


@runtime_checkable
class SchemaRepository(Protocol):
    def get_by_name(
        self, name: str, include_deleted: bool = False
    ) -> SchemaDTO | None: ...
    def get_by_id(
        self, id: uuid.UUID, include_deleted: bool = False
    ) -> SchemaDTO | None: ...
    def list_all(self) -> list[SchemaDTO]: ...
    def list_deleted(self) -> list[SchemaDTO]: ...
    def create(
        self,
        name: str,
        description: str | None,
        parent_id: uuid.UUID | None,
        label: str | None = None,
    ) -> SchemaDTO: ...
    def update(
        self,
        id: uuid.UUID,
        name: str | None,
        description: str | None,
        display_template: str | None = ...,
        label: str | None = ...,
        unique_keys: list[list[str]] | None = ...,
    ) -> SchemaDTO: ...
    def delete(self, id: uuid.UUID, stamp: datetime | None = None) -> None: ...
    def restore(self, id: uuid.UUID) -> SchemaDTO: ...
    def cascade_count(self, id: uuid.UUID) -> int: ...
    def purge(self, id: uuid.UUID) -> None: ...
    def add_field(
        self,
        schema_id: uuid.UUID,
        name: str,
        dtype: str,
        required: bool,
        restrictions: dict[str, Any],
        default_value: Any = None,
        position: int | None = None,
        label: str | None = None,
    ) -> FieldDTO: ...
    def update_field(
        self,
        field_id: uuid.UUID,
        *,
        name: str | None = None,
        required: bool | None = None,
        restrictions: dict | None = None,
        default_value: Any = ...,
        label: str | None = ...,
    ) -> FieldDTO: ...
    def delete_field(
        self, field_id: uuid.UUID, stamp: datetime | None = None
    ) -> None: ...
    def restore_field(self, field_id: uuid.UUID) -> FieldDTO: ...
    def find_fields(self, ids: set[uuid.UUID]) -> dict[uuid.UUID, FieldDTO]: ...
    def get_fields(self, schema_id: uuid.UUID) -> list[FieldDTO]: ...
    def reorder_fields(
        self, schema_id: uuid.UUID, field_ids: list[uuid.UUID]
    ) -> list[FieldDTO]: ...


@runtime_checkable
class DatasetRepository(Protocol):
    def get_by_name(
        self,
        name: str,
        include_deleted: bool = False,
        with_count: bool = True,
        with_schemas: bool = True,
    ) -> DatasetDTO | None:
        """`with_count=False` skips the live-record count (an O(records) scan)
        and leaves `record_count` at 0; `with_schemas=False` skips the schema
        list lookup and leaves `schemas` empty -- for callers that don't read
        them."""
        ...

    def get_by_id(
        self,
        id: uuid.UUID,
        include_deleted: bool = False,
        with_count: bool = True,
        with_schemas: bool = True,
    ) -> DatasetDTO | None: ...
    def list_all(self, with_count: bool = True) -> list[DatasetDTO]: ...
    def list_deleted(self) -> list[DatasetDTO]: ...
    def create(
        self,
        name: str,
        description: str | None,
        timezone: str | None = None,
        scope: str = "local",
    ) -> DatasetDTO: ...
    def update(
        self,
        id: uuid.UUID,
        name: str | None,
        description: str | None,
        timezone: str | None = None,
        scope: str | None = None,
    ) -> DatasetDTO: ...
    def set_schemas(self, id: uuid.UUID, schema_names: list[str]) -> DatasetDTO:
        """Replace the collection's schema list (names must be live schemas)."""
        ...

    def schemas_in_use(self, id: uuid.UUID) -> set[str]:
        """Names of the schemas live records in the collection are typed by."""
        ...

    def delete(self, id: uuid.UUID, stamp: datetime | None = None) -> None: ...
    def restore(self, id: uuid.UUID) -> DatasetDTO: ...
    def cascade_count(self, id: uuid.UUID) -> int: ...
    def purge(self, id: uuid.UUID) -> None: ...


@runtime_checkable
class ViewRepository(Protocol):
    def get_by_id(self, id: uuid.UUID) -> ViewDTO | None: ...
    def get_by_name(self, schema_id: uuid.UUID, name: str) -> ViewDTO | None: ...
    def list_by_schema(self, schema_id: uuid.UUID) -> list[ViewDTO]: ...
    def list_all(self) -> list[ViewDTO]: ...
    def create(
        self,
        schema_id: uuid.UUID,
        name: str,
        columns: list[str],
        filter_tree: dict[str, Any] | None,
        sort: list[dict[str, Any]],
        files_layout: str = ...,
    ) -> ViewDTO: ...
    def update(
        self,
        id: uuid.UUID,
        name: str | None,
        columns: list[str] = ...,
        filter_tree: dict[str, Any] | None = ...,
        sort: list[dict[str, Any]] = ...,
        files_layout: str = ...,
    ) -> ViewDTO: ...
    def delete(self, id: uuid.UUID) -> None: ...


class ExportDefinitionRepository(Protocol):
    def get_by_name(
        self, schema_id: uuid.UUID, name: str
    ) -> ExportDefinitionDTO | None: ...
    def list_by_schema(self, schema_id: uuid.UUID) -> list[ExportDefinitionDTO]: ...
    def list_for_schemas(
        self, schema_ids: list[uuid.UUID]
    ) -> list[ExportDefinitionDTO]: ...
    def list_all(self) -> list[ExportDefinitionDTO]: ...
    def create(
        self,
        schema_id: uuid.UUID,
        name: str,
        holder_id: uuid.UUID | None,
        fields: list[str],
        filter_tree: dict[str, Any] | None,
        files_layout: str,
        include_files: bool = True,
        tables: list[dict[str, Any]] | None = None,
    ) -> ExportDefinitionDTO: ...
    def update(
        self,
        id: uuid.UUID,
        name: str | None = None,
        holder_id: uuid.UUID | None = ...,
        fields: list[str] = ...,
        filter_tree: dict[str, Any] | None = ...,
        files_layout: str = ...,
        include_files: bool = ...,
        tables: list[dict[str, Any]] = ...,
    ) -> ExportDefinitionDTO: ...
    def delete(self, id: uuid.UUID) -> None: ...


@runtime_checkable
class RecordRepository(Protocol):
    def get_by_id(
        self, id: uuid.UUID, include_deleted: bool = False
    ) -> RecordDTO | None: ...
    def get_by_prefix(
        self, prefix: str, include_deleted: bool = False
    ) -> RecordDTO | None: ...
    def list_all(self) -> list[RecordDTO]: ...
    def find_key_match(
        self,
        dataset_id: uuid.UUID,
        schema_id: uuid.UUID,
        parent_record_id: uuid.UUID | None,
        key: dict[str, Any],
        exclude_id: uuid.UUID | None = None,
        include_deleted: bool = False,
    ) -> RecordDTO | None: ...
    def live_schema_ids(self, dataset_id: uuid.UUID) -> set[uuid.UUID]: ...
    def deleted_states(
        self,
        *,
        schema_id: uuid.UUID | None = None,
        dataset_id: uuid.UUID | None = None,
    ) -> dict[uuid.UUID, datetime | None]: ...
    def key_duplicates(
        self, schema_id: uuid.UUID, field_ids: list[str]
    ) -> list[list[uuid.UUID]]: ...
    def list_deleted(
        self,
        dataset_id: uuid.UUID | None = None,
        offset: int = 0,
        limit: int | None = None,
    ) -> list[RecordDTO]: ...
    def list_by_dataset(self, dataset_id: uuid.UUID) -> list[RecordDTO]: ...
    def list_by_ids(self, ids: list[uuid.UUID]) -> list[RecordDTO]: ...
    def list_filtered(
        self,
        query: ResolvedQuery,
        offset: int,
        limit: int,
        after: tuple[datetime, uuid.UUID] | None = None,
    ) -> list[RecordDTO]: ...
    def count(self, query: ResolvedQuery) -> int: ...
    def list_ids(self, query: ResolvedQuery) -> list[uuid.UUID]: ...
    def count_by_schema(self, query: ResolvedQuery) -> dict[str, int]: ...
    def count_children(
        self, parent_ids: list[uuid.UUID]
    ) -> dict[uuid.UUID, dict[str, int]]: ...
    def growth_by_period(
        self,
        dataset_id: uuid.UUID | None,
        schema_id: uuid.UUID | None,
        start: datetime | None,
        end: datetime | None,
    ) -> list[RecordGrowthRow]: ...
    def list_by_schema(
        self,
        schema_id: uuid.UUID,
        search: str | None = None,
        limit: int = 20,
        dataset_ids: list[uuid.UUID] | None = None,
    ) -> list[RecordDTO]: ...
    def search_all(
        self,
        search: str,
        limit: int = 20,
        dataset_id: uuid.UUID | None = None,
    ) -> list[RecordDTO]: ...
    def count_schema_matches(
        self, schema_id: uuid.UUID, search: str | None = None
    ) -> int: ...
    def count_by_schema_ids(self, schema_ids: list[uuid.UUID]) -> int: ...
    def list_children(
        self, parent_id: uuid.UUID, include_deleted: bool = False
    ) -> list[RecordDTO]: ...
    def list_children_of(self, parent_ids: list[uuid.UUID]) -> list[RecordDTO]: ...
    def referrers_of(
        self, target_ids: list[uuid.UUID], field_ids: list[uuid.UUID]
    ) -> list[tuple[uuid.UUID, uuid.UUID, uuid.UUID]]:
        """(referrer id, field id, target id) for live records whose value in
        one of `field_ids` points at any of `target_ids`."""
        ...

    def referrer_groups(
        self, target_id: uuid.UUID, field_ids: list[uuid.UUID]
    ) -> list[tuple[uuid.UUID, str, uuid.UUID, int]]:
        """Live referrers of a record counted per (collection id, schema name,
        field id)."""
        ...

    def referrers_into_dataset(
        self, dataset_id: uuid.UUID, field_ids: list[uuid.UUID], limit: int
    ) -> tuple[int, list[tuple[uuid.UUID, uuid.UUID]]]:
        """Records in other collections pointing into `dataset_id`: their
        number, and (record id, field id) pairs for the first `limit`."""
        ...

    def dangling_references(
        self, field_ids: list[uuid.UUID]
    ) -> list[tuple[uuid.UUID, str, uuid.UUID, uuid.UUID]]:
        """(record id, schema name, field id, target id) for values naming no
        live record."""
        ...

    def create(
        self,
        dataset_id: uuid.UUID,
        schema_id: uuid.UUID,
        data: dict[str, Any],
        parent_record_id: uuid.UUID | None = None,
    ) -> RecordDTO: ...
    def update(self, id: uuid.UUID, data: dict[str, Any]) -> RecordDTO: ...
    def delete(self, id: uuid.UUID) -> None: ...
    def restore(self, id: uuid.UUID) -> RecordDTO: ...
    def purge(self, id: uuid.UUID) -> None: ...
    def subtree_levels(
        self, root_ids: list[uuid.UUID], deleted: bool | None = None
    ) -> list[list[uuid.UUID]]:
        """Records under `root_ids` a level at a time (roots first), one query
        per level. `deleted`: False = live only, True = deleted only."""
        ...

    def purgeable_deleted(
        self, cutoff: datetime
    ) -> list[tuple[uuid.UUID, uuid.UUID, uuid.UUID]]: ...
    def delete_many(
        self, ids: list[uuid.UUID], stamp: datetime | None = None
    ) -> None: ...
    def restore_many(self, ids: list[uuid.UUID]) -> None: ...
    def live_under_deleted(self, limit: int) -> tuple[list[RecordDTO], int]: ...
    def purge_many(self, ids: list[uuid.UUID]) -> None: ...


@runtime_checkable
class WorkflowJobRepository(Protocol):
    def count_finished_before(self, before: datetime) -> tuple[int, int]: ...
    def delete_jobs(self, ids: list[uuid.UUID]) -> int: ...
    def delete_finished_before(self, before: datetime) -> int: ...
    def enqueue(
        self,
        workflow_name: str,
        record_id: uuid.UUID,
        trigger: str,
        input_data: dict | None = None,
        depth: int = 0,
        trigger_detail: dict | None = None,
    ) -> WorkflowJobDTO: ...
    def claim_pending(self) -> WorkflowJobDTO | None: ...
    def status_of(self, job_id: uuid.UUID) -> str | None: ...
    def cancel(self, job_id: uuid.UUID, reason: str) -> WorkflowJobDTO | None: ...
    def cancel_all_active(self, reason: str) -> int: ...
    def mark_cancelled(
        self,
        job_id: uuid.UUID,
        log: str | None = None,
        step_executions: list[dict] | None = None,
        affected_records: list[dict] | None = None,
    ) -> None: ...
    def mark_completed(
        self,
        job_id: uuid.UUID,
        log: str | None = None,
        step_executions: list[dict] | None = None,
        affected_records: list[dict] | None = None,
    ) -> None: ...
    def mark_failed(
        self,
        job_id: uuid.UUID,
        error_details: dict,
        log: str | None = None,
        step_executions: list[dict] | None = None,
        affected_records: list[dict] | None = None,
    ) -> None: ...
    def list_all(
        self,
        status: str | None = None,
        record_id: str | None = None,
        affected_record_id: str | None = None,
        offset: int = 0,
        limit: int | None = None,
        affected_schema: str | None = None,
        trigger: str | None = None,
        search: str | None = None,
        sort: str | None = None,
        workflow: str | None = None,
        where: FilterNode | None = None,
    ) -> list[WorkflowJobDTO]: ...
    def count(
        self,
        status: str | None = None,
        record_id: str | None = None,
        affected_record_id: str | None = None,
        affected_schema: str | None = None,
        trigger: str | None = None,
        search: str | None = None,
        workflow: str | None = None,
        where: FilterNode | None = None,
    ) -> int: ...
    def ids_matching(self, where: FilterNode | None, limit: int) -> list[uuid.UUID]: ...
    def failure_groups(self, where: FilterNode | None) -> list[dict]: ...
    def batch_stats(self) -> dict | None: ...
    def get_by_id(self, job_id: uuid.UUID) -> WorkflowJobDTO | None: ...
    def count_active_for_workflow(self, workflow_name: str) -> int: ...
    def failure_counts_by_plugin(
        self,
        start: datetime | None = None,
        end: datetime | None = None,
        bucket: str | None = None,
    ) -> dict[str, int] | list[PluginFailureRow]: ...
    def status_counts_by_period(
        self,
        start: datetime | None,
        end: datetime | None,
        workflow_name: str | None,
        trigger: str | None,
        status: str | None,
    ) -> list[JobStatusRow]: ...
    def step_durations(
        self,
        start: datetime | None,
        end: datetime | None,
        plugin: str | None,
        status: str | None,
    ) -> list[float]: ...
    def trigger_counts(
        self,
        start: datetime | None,
        end: datetime | None,
        workflow_name: str | None,
        status: str | None,
        trigger: str | None,
    ) -> list[TriggerCountRow]: ...


@runtime_checkable
class AiUsageRepository(Protocol):
    def add(
        self, provider: str, model: str, input_tokens: int, output_tokens: int
    ) -> AiUsageEventDTO: ...
    def list_all(
        self,
        since: datetime | None = None,
        until: datetime | None = None,
        provider: str | None = None,
        model: str | None = None,
    ) -> list[AiUsageEventDTO]: ...


@runtime_checkable
class AuditRepository(Protocol):
    """Write-side audit interface used by services to record changes."""

    def log_change(
        self,
        action: str,
        entity_type: str,
        entity_id: uuid.UUID,
        old_data: dict | None,
        new_data: dict | None,
        timestamp: datetime | None = None,
        op: uuid.UUID | None = None,
    ) -> None: ...
    def operation(self) -> AbstractContextManager[None]: ...
    def count_whole_edits(self) -> int: ...
    def whole_edits(
        self, limit: int, after: uuid.UUID | None = None
    ) -> list[AuditLogDTO]: ...
    def store_as_delta(
        self,
        entry_id: uuid.UUID,
        new_data: dict | None,
        delta: dict | None,
        form: int,
    ) -> None: ...
    def get_audit(self, audit_id: uuid.UUID) -> AuditLogDTO | None: ...
    def find_audit(self, prefix: str) -> list[AuditLogDTO]: ...
    def list_audit(
        self,
        limit: int = 50,
        offset: int = 0,
        sort: str | None = None,
        **filters: Any,
    ) -> list[AuditLogDTO]: ...
    def count_audit(self, **filters: Any) -> int: ...
    def list_events(
        self,
        f: AuditFilter,
        limit: int = 25,
        offset: int = 0,
        newest_first: bool = True,
    ) -> tuple[list[AuditEventDTO], int]: ...
    def batch(
        self, kind: str, label: str | None = None, ref: str | None = None
    ) -> AbstractContextManager[None]: ...
    def open_batch(
        self, kind: str, label: str | None = None, ref: str | None = None
    ) -> AuditBatchDTO: ...
    def join_batch(self, batch_id: uuid.UUID) -> bool: ...
    def get_batch(self, batch_id: uuid.UUID) -> AuditBatchDTO | None: ...
    def entities(
        self, f: AuditFilter, limit: int
    ) -> tuple[list[tuple[str, uuid.UUID]], bool]: ...
    def batch_parts(self, batch_id: uuid.UUID) -> list[dict]: ...
    def count_prunable(
        self, before: datetime, protect_unsynced: bool
    ) -> dict[str, int]: ...
    def prune(self, before: datetime, protect_unsynced: bool) -> tuple[int, int]: ...
    def forget_records(self, ids: list[uuid.UUID]) -> int: ...
    def forget_records_matching(self, needle: str) -> int: ...
    def count_orphaned_records(self) -> int: ...
    def forget_orphaned_records(self) -> int: ...
    def event_counts_by_period(
        self,
        start: datetime | None,
        end: datetime | None,
        entity_type: str | None = None,
        action: str | None = None,
    ) -> list[AuditEventRow]: ...


@runtime_checkable
class FileObjectStore(Protocol):
    """
    Content-addressed blob store.
    Implementations: LocalFileObjectStore (_civex/objects/), future S3Store.
    """

    # `collection_id` is an optional placement hint: where *new* content goes.
    # Content that is already stored is reused, never copied again.
    def put(
        self, data: bytes, original_filename: str, collection_id: str | None = None
    ) -> FileRef: ...
    async def put_stream(
        self,
        chunks: AsyncIterable[bytes],
        original_filename: str,
        size_hint: int | None = None,
        collection_id: str | None = None,
    ) -> FileRef: ...
    def get(self, sha256: str) -> bytes: ...
    def exists(self, sha256: str) -> bool: ...
    def copies(self, shas: Iterable[str]) -> dict[str, list[tuple[str, int]]]: ...
    def readable_first(self, volumes: Iterable[str]) -> list[str]: ...
    def homes(self) -> dict[str, str]: ...
    def locate_volumes(self, shas: Iterable[str]) -> dict[str, str | None]: ...
    def copies_of(self, sha256: str) -> list[FileCopy]: ...
    def size_of(self, sha256: str) -> int | None: ...
    def volume_status(self, name: str) -> VolumeStatus: ...
    def offline_location(self, sha256: str) -> tuple[str, VolumeStatus] | None: ...
    # -- transfers: see civex.services.transfer_engine ------------------------
    def iter_volume_objects(self, name: str) -> Iterator[StoredObjectInfo]: ...
    def volume_path(self, name: str) -> Path: ...
    def can_accept(self, volume: str, size: int) -> tuple[bool, str]: ...
    def object_size(self, sha256: str, volume: str) -> int: ...
    def transfer_object(
        self,
        sha256: str,
        source: str,
        target: str,
        *,
        verify: str = "copy",
        on_chunk: Callable[[int], None] | None = None,
    ) -> CopyResult: ...
    def record_moves(
        self,
        added: list[tuple[str, str, int]],
        removed: list[tuple[str, str]] = ...,
    ) -> None: ...
    def remove_from_volume(self, sha256: str, volume: str) -> bool: ...
    def read_manifest_names(self, volume: str) -> dict[str, str]: ...
    def append_manifest(
        self, volume: str, sha256: str, filename: str | None, size: int
    ) -> None: ...
    def inventory_totals(
        self, volumes: Iterable[str]
    ) -> dict[str, tuple[int, int]]: ...
    def room_on(self, volume: str) -> int | None: ...
    def transfer_lock(self) -> ContextManager[None]: ...
    def touch_transfer_lock(self) -> None: ...
    def transfer_lock_held(self) -> bool: ...
    def object_path(self, sha256: str) -> Path: ...
    def path_on(self, sha256: str, volume: str) -> Path: ...
    def list_objects(self) -> list[StoredObjectInfo]: ...
    def iter_objects(self) -> Iterator[StoredObjectInfo]: ...
    def volume_names(self) -> list[str]: ...
    def put_path(
        self,
        path: Path,
        original_filename: str | None = None,
        collection_id: str | None = None,
        volume: str | None = None,
    ) -> FileRef: ...
    def put_chunks(
        self,
        chunks: Iterable[bytes],
        original_filename: str,
        size_hint: int | None = None,
        collection_id: str | None = None,
        volume: str | None = None,
    ) -> FileRef: ...
    def reconcile_inventory(self) -> dict[str, int]: ...
    def delete(self, sha256: str, volume: str | None = None) -> bool: ...
    def sweep_stale_scratch(
        self, older_than_seconds: float, dry_run: bool = False
    ) -> int: ...
    def gc_lock(self) -> ContextManager[None]: ...


class FileReferenceRepository(Protocol):
    """Which blobs are referenced by live records / workflow job inputs."""

    def referenced_subset(self, shas: Iterable[str]) -> set[str]: ...
    def usage(self, sha256: str) -> tuple[dict[uuid.UUID | None, int], int, int]: ...
    def shas_for_collections(
        self, collection_ids: list[str], after: str | None, limit: int
    ) -> list[str]: ...
    def collections_using(self, shas: Iterable[str]) -> dict[str, set[str]]: ...
    def records_using(self, shas: Iterable[str]) -> dict[str, set[uuid.UUID]]: ...
    def surplus_by_volume(self) -> dict[str, tuple[int, int, int, int]]: ...
    def volume_breakdowns(
        self, collection_ids: list[str] | None, homes: dict[str, str] | None = None
    ) -> dict[str, tuple[int, list[tuple[str, int, int, int]]]]: ...
    def count_referenced(self) -> int: ...
    def rebuild(self) -> int: ...


@runtime_checkable
class TransferRepository(Protocol):
    """The saved account of storage transfers."""

    def create(self, record: TransferRecord) -> None: ...
    def get(self, transfer_id: str) -> TransferRecord | None: ...
    def recent(self, limit: int = 50) -> list[TransferRecord]: ...
    def running(self) -> list[TransferRecord]: ...
    def queued(self) -> list[TransferRecord]: ...
    def waiting_for_volumes(self) -> list[TransferRecord]: ...
    def save(self, record: TransferRecord) -> None: ...
    def control(self, transfer_id: str) -> str | None: ...
    def set_control(self, transfer_id: str, value: str | None) -> None: ...


@runtime_checkable
class SyncRepository(Protocol):
    """Sync's storage; see `repositories.local.sync_repo`."""

    def add_conflict(
        self,
        *,
        kind: str,
        entity_type: str,
        entity_id: uuid.UUID,
        field: str | None,
        yours: Any,
        theirs: Any,
        op_id: uuid.UUID | None,
        device_name: str | None,
        message: str | None,
        base: Any = None,
        theirs_actor: str | None = None,
        theirs_at: str | None = None,
        theirs_device: str | None = None,
    ) -> SyncConflictDTO: ...
    def last_change(
        self, kind: str, entity_id: uuid.UUID, path: str | None
    ) -> tuple[str | None, str | None, str | None]: ...
    def add_device(
        self, name: str, device_id: str, public_key: str
    ) -> SyncDeviceDTO: ...
    def add_invite(
        self, name: str, code_hash: str, expires_at: datetime
    ) -> SyncInviteDTO: ...
    def apply_snapshot(self, kind: str, snap: dict[str, Any]) -> None: ...
    def authority_key(self) -> str | None: ...
    def count_conflicts(self, status: str | None = "open") -> int: ...
    def count_pending(self) -> int: ...
    def delete_view(self, id: uuid.UUID) -> None: ...
    def cancel_invite(self, name: str) -> bool: ...
    def device_named(self, name: str) -> SyncDeviceDTO | None: ...
    def get_device(self, id: uuid.UUID) -> SyncDeviceDTO | None: ...
    def invite_by_hash(self, code_hash: str) -> SyncInviteDTO | None: ...
    def live_device(self, device_id: str) -> SyncDeviceDTO | None: ...
    def pending_invites(self) -> list[SyncInviteDTO]: ...
    def dirty_entities(self) -> set[tuple[str, uuid.UUID]]: ...
    def drop_op(self, op_id: uuid.UUID) -> None: ...
    def entity_count(self) -> int: ...
    def entity_counts(self) -> dict[str, int]: ...
    def set_history_from(self, seq: int | None) -> None: ...
    def history_fetched_upto(self, upto: int) -> int: ...
    def entries_after(self, seq: int, limit: int) -> tuple[list[SyncEntry], bool]: ...
    def get_conflict(self, id: uuid.UUID) -> SyncConflictDTO | None: ...
    def get_op(self, op_id: uuid.UUID) -> OpResult | None: ...
    def has_conflict(self, op_id: uuid.UUID, field: str | None, kind: str) -> bool: ...
    def get_entry(self, id: uuid.UUID) -> SyncEntry | None: ...
    def has_entry(self, id: uuid.UUID) -> bool: ...
    def head_seq(self) -> int: ...
    def insert_entry(
        self,
        entry: SyncEntry,
        *,
        hub_seq: int | None,
        state: str = "synced",
        apply_state: str = "applied",
    ) -> None: ...
    def held_entries(self) -> list[SyncEntry]: ...
    def mark_applied(self, entry_ids: list[uuid.UUID]) -> None: ...
    def latest_hlc(self) -> str | None: ...
    def list_conflicts(
        self,
        status: str | None = "open",
        limit: int = 200,
        offset: int = 0,
        entity_id: uuid.UUID | None = None,
    ) -> list[SyncConflictDTO]: ...
    def list_devices(self) -> list[SyncDeviceDTO]: ...
    def mark_all_synced(self) -> None: ...
    def mark_sent(self, results: list[OpResult]) -> None: ...
    def mark_seq(
        self, entry_id: uuid.UUID, seq: int, device: str | None = None
    ) -> None: ...
    def meta(self) -> SyncMetaDTO: ...
    def next_hub_seq(self) -> int: ...
    def pending_entries(self, limit: int) -> list[SyncEntry]: ...
    def purge(self, kind: str, id: uuid.UUID) -> None: ...
    def record_outcome(self, error: str | None) -> None: ...
    def resolve_conflict(self, id: uuid.UUID, resolution: str) -> None: ...
    def conflicts_of_ops(self, op_ids: list[uuid.UUID]) -> list[SyncConflictDTO]: ...
    def find_open_conflicts(
        self,
        *,
        ids: list[uuid.UUID] | None = None,
        kind: str | None = None,
        entity_id: uuid.UUID | None = None,
    ) -> list[SyncConflictDTO]: ...
    def resolve_conflicts(self, ids: list[uuid.UUID], resolution: str) -> int: ...
    def reopen_conflicts(self, ids: list[uuid.UUID], resolution: str) -> int: ...
    def restore(self, kind: str, id: uuid.UUID) -> None: ...
    def revoke_device(self, name: str) -> bool: ...
    def set_may_publish(self, name: str, allowed: bool) -> bool: ...
    def save_op(
        self,
        entry: SyncEntry,
        result: OpResult,
        device_id: str | None,
        device_name: str | None,
    ) -> None: ...
    def sequence_local_entries(self) -> int: ...
    def lock_feed(self) -> None: ...
    def entries_of_action(self, op: str) -> list[SyncEntry]: ...
    def never_taken(self, things: set[tuple[str, uuid.UUID]]) -> set[uuid.UUID]: ...
    def forget_numbers(self) -> None: ...
    def mark_retrying(self, id: uuid.UUID) -> None: ...
    def renew_refusal(
        self,
        id: uuid.UUID,
        op_id: uuid.UUID,
        message: str | None,
        yours: Any,
        field: str | None = None,
    ) -> None: ...
    def mark_folded(self, entry_ids: list[uuid.UUID], state: str) -> None: ...
    def numbered_entries(
        self, kind: str, entity_id: uuid.UUID, from_seq: int
    ) -> list[SyncEntry]: ...
    def existing_ids(self, kind: str, ids: set[str]) -> set[str]: ...
    def all_ids(self, kind: str) -> set[str]: ...
    def begin_seed(self) -> None: ...
    def finish_seed(self) -> None: ...
    def set_cursor(self, seq: int) -> None: ...
    def referenced_shas(self, after: str, limit: int) -> list[str]: ...
    def files_not_here(
        self,
        after: str,
        limit: int,
        shas: list[str] | None = None,
        collections: set[uuid.UUID] | None = None,
    ) -> list[tuple[str, uuid.UUID | None]]: ...
    def count_files_not_here(
        self, collections: set[uuid.UUID] | None = None
    ) -> int: ...
    def files_by_collection(self) -> dict[uuid.UUID, tuple[int, int, int]]: ...
    def added_by(self, shas: list[str]) -> dict[str, str | None]: ...
    def live_collections(self) -> dict[uuid.UUID, str]: ...
    def files_here_of(self, collection: uuid.UUID) -> dict[str, int]: ...
    def used_by(self, shas: list[str], collections: set[uuid.UUID]) -> set[str]: ...
    def set_project_id(self, project_id: uuid.UUID) -> None: ...
    def set_authority_key(self, key: str) -> None: ...
    def set_seeded_by(self, device_id: str) -> None: ...
    def snapshot(self, kind: str, id: uuid.UUID) -> dict[str, Any] | None: ...
    def snapshots_page(
        self, kind: str, after: str | None, limit: int
    ) -> list[dict[str, Any]]: ...
    def record_seed_order(self) -> list[str]: ...
    def record_snapshots(self, ids: list[str]) -> list[dict[str, Any]]: ...
    def soft_delete(self, kind: str, id: uuid.UUID, stamp: datetime) -> None: ...
    def touch_device(self, id: uuid.UUID) -> None: ...
    def use_invite(self, id: uuid.UUID) -> bool: ...
    def savepoint(self) -> AbstractContextManager[None]: ...


class LibraryRepository(Protocol):
    """The authority's library of shared workflows and plugins."""

    def all(self) -> list[LibraryItemDTO]: ...
    def get(self, kind: str, name: str) -> LibraryItemDTO | None: ...
    def count(self) -> int: ...
    def provider_of(self, plugin_id: str) -> str | None: ...
    def put(self, item: LibraryItemDTO) -> LibraryItemDTO: ...
    def remove(self, kind: str, name: str) -> bool: ...
