"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-07-12 22:54:11.627146
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import civex.db.models

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("schema_count", sa.Integer(), nullable=False),
        sa.Column("dataset_count", sa.Integer(), nullable=False),
        sa.Column(
            "pushed_at", civex.db.models._UTCDateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "schemas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("display_field", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commit_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "old_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "new_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "timestamp", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fields",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schema_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dtype", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column(
            "restrictions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "default_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schema_id", "name"),
    )
    op.create_table(
        "records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("schema_id", sa.Uuid(), nullable=False),
        sa.Column("parent_record_id", sa.Uuid(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "search_vector",
            sa.Text().with_variant(postgresql.TSVECTOR(), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_record_id"],
            ["records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["schemas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_records_data_gin", "records", ["data"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_records_dataset_created",
        "records",
        ["dataset_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_records_dataset_parent",
        "records",
        ["dataset_id", "parent_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_records_dataset_schema",
        "records",
        ["dataset_id", "schema_id"],
        unique=False,
    )
    op.create_table(
        "workflow_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_name", sa.String(length=255), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=255), nullable=False),
        sa.Column("trigger", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("log", sa.String(), nullable=True),
        sa.Column(
            "input_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at", civex.db.models._UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "started_at", civex.db.models._UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "finished_at", civex.db.models._UTCDateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_jobs")
    op.drop_index("ix_records_dataset_schema", table_name="records")
    op.drop_index("ix_records_dataset_parent", table_name="records")
    op.drop_index("ix_records_dataset_created", table_name="records")
    op.drop_index("ix_records_data_gin", table_name="records", postgresql_using="gin")
    op.drop_table("records")
    op.drop_table("fields")
    op.drop_table("audit_log")
    op.drop_table("schemas")
    op.drop_table("datasets")
    op.drop_table("commits")
    # ### end Alembic commands ###
